//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public Car()
        {
            this.Seats = new HashSet<Seat>();
        }
    
        public long ID { get; set; }
        public long TrainID { get; set; }
        public long Number { get; set; }
    
        public virtual Train Train { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
