//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public long ID { get; set; }
        public long PassportNumber { get; set; }
        public long TrainID { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Train Train { get; set; }
    }
}
