//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Passenger
    {
        public Passenger()
        {
            this.Histories = new HashSet<History>();
            this.Seats = new HashSet<Seat>();
        }
    
        public long PassportNumber { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<History> Histories { get; set; }
        public virtual ICollection<Seat> Seats { get; set; }
    }
}
