//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrainSystem.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seat
    {
        public long ID { get; set; }
        public long CarID { get; set; }
        public string Coordinates { get; set; }
        public bool Available { get; set; }
        public Nullable<long> PassengerPassport { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Passenger Passenger { get; set; }
    }
}
